### ISSUE TITLE
Clean "%s" from user input

### ISSUE THREAD

**Issue by andrewtwatson** [andrewtwatson/GroupMePrayer#7]
The template for creating a message uses "%s" for each slot to slide in a parameter. If a user used %s in their name or prayer request, it would really break stuff. We need a way to sanitize inputs from using really any % signs at all.

**Comment by brunoacpcosta** [comment]
Hi can I help with this one? I would like to contribute and thought about using different types of format such as f"{ Example }".

**Comment by andrewtwatson** [comment]
Thanks for your help!
